web:
  build: .
  command: python /code/app/app.py
  ports:
    - "5000:5000"
  #volumes:
  # - .:/code
  links:
    - db
  hostname: myappserver
db:
  hostname: mysqlserver
  image: mysql:latest
  environment:
     MYSQL_ROOT_PASSWORD: hina
     MYSQL_DATABASE: expensedb
  volumes:
- /var/lib/mysql